# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3be4827633d3a0a356842a0c32a2f22b07720a7f5660d086a75b61ff29c2caf6112702ba6d2db03902d3c463879c765cf34a7e9116b206d1e201ba21713497e0

test:
  secret_key_base: 21efa4d832e9b865928383537809b8241ef4c65ff96b54e99b1ce8d99fd6ead4457ca3cbd8856d388689ea3a5244ddf05558f1849efeed062b0ddcbb27239286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
